[package]
name = "chal8"
version = "0.1.0"
authors = ["arturo <arturomf94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
openssl = "0.10.29"
